### ISSUE TITLE
large/ish folders broken 

### ISSUE THREAD

**Issue by srepmub** [Dionach/PANhunt#5]
thanks for the very nicely written pst.py! I was building something similar, until I found this. I would love to help push this as "python-pst" into for example debian, to give it a bit more visibility.. 

I found a pretty serious bug though (just one for now), which causes large folders to appear empty. the following makes the problem obvious ('bytes' doesn't change!), and fixes it for my current test case (no mail in large inbox):

bth_intermediate = bth_working_stack.pop()
+bytes = hn.get_hid_data(bth_intermediate.hidNextLevel)

cheers, thanks again.

**Comment by bli-dn** [comment]
I haven't looked at this in a while! Glad you're using it. How many items are in your large folder, so I can reproduce?

**Comment by srepmub** [comment]
thanks! 539, so not really that large actually.. :)
